#
# Purgatory ia64
#
PURGATORY_SRCS += purgatory/arch/ia64/entry.S
PURGATORY_SRCS += purgatory/arch/ia64/purgatory-ia64.c
PURGATORY_SRCS += purgatory/arch/ia64/console-ia64.c
PURGATORY_SRCS += purgatory/arch/ia64/vga.c

$(PURGATORY): CFLAGS += -ffixed-r28

