#
# kexec mipsel (linux booting linux)
#
KEXEC_C_SRCS+= kexec/arch/mipsel/kexec-mipsel.c
KEXEC_C_SRCS+= kexec/arch/mipsel/kexec-elf-mipsel.c
KEXEC_C_SRCS+= kexec/arch/mipsel/kexec-elf-rel-mipsel.c
KEXEC_S_SRCS+= kexec/arch/mipsel/mipsel-setup-simple.S
