#
# Purgatory x86_64
#

PURGATORY_S_SRCS+= purgatory/arch/i386/entry32-16.S
PURGATORY_S_SRCS+= purgatory/arch/i386/entry32-16-debug.S
PURGATORY_S_SRCS+= purgatory/arch/x86_64/entry64-32.S
PURGATORY_S_SRCS+= purgatory/arch/x86_64/entry64.S
PURGATORY_S_SRCS+= purgatory/arch/x86_64/setup-x86_64.S
PURGATORY_S_SRCS+= purgatory/arch/x86_64/stack.S
PURGATORY_C_SRCS+= purgatory/arch/x86_64/purgatory-x86_64.c
PURGATORY_C_SRCS+= purgatory/arch/i386/crashdump_backup.c
PURGATORY_C_SRCS+= purgatory/arch/i386/console-x86.c
PURGATORY_C_SRCS+= purgatory/arch/i386/vga.c
PURGATORY_C_SRCS+= purgatory/arch/i386/pic.c

