#
# kexec ppc (linux booting linux)
#
KEXEC_C_SRCS+= kexec/arch/ppc/kexec-ppc.c 
KEXEC_C_SRCS+= kexec/arch/ppc/kexec-elf-ppc.c 
KEXEC_C_SRCS+= kexec/arch/ppc/kexec-elf-rel-ppc.c
KEXEC_C_SRCS+= kexec/arch/ppc/kexec-dol-ppc.c
KEXEC_S_SRCS+= kexec/arch/ppc/ppc-setup-simple.S
KEXEC_S_SRCS+= kexec/arch/ppc/ppc-setup-dol.S
