#
# kexec sh (linux booting linux)
#
KEXEC_SRCS += kexec/arch/sh/kexec-sh.c
KEXEC_SRCS += kexec/arch/sh/kexec-zImage-sh.c
KEXEC_SRCS += kexec/arch/sh/kexec-netbsd-sh.c
KEXEC_SRCS += kexec/arch/sh/kexec-elf-rel-sh.c
KEXEC_SRCS += kexec/arch/sh/netbsd_booter.S
