#
# Purgatory mipsel
#

mipsel_PURGATORY_C_SRCS+= purgatory/arch/mipsel/purgatory-mipsel.c
mipsel_PURGATORY_C_SRCS+= purgatory/arch/mipsel/console-mipsel.c

dist += purgatory/arch/mipsel/Makefile $(mipsel_PURGATORY_C_SRCS)	\
	purgatory/arch/mipsel/include/limits.h				\
	purgatory/arch/mipsel/purgatory-mipsel.h

