#
# Purgatory mips
#

mips_PURGATORY_SRCS+= purgatory/arch/mips/purgatory-mips.c
mips_PURGATORY_SRCS+= purgatory/arch/mips/console-mips.c

dist += purgatory/arch/mips/Makefile $(mips_PURGATORY_C_SRCS)		\
	purgatory/arch/mips/include/limits.h				\
	purgatory/arch/mips/purgatory-mips.h

